site_name: BRL-CAD Wiki
site_url: https://brl-cad.github.io/wiki/
repo_url: https://github.com/BRL-CAD/wiki/
edit_uri: blob/main/pages/
remote_branch: gh-pages

docs_dir: pages
site_dir: html

#theme:
#  name: mkdocs
#  locale: en
#  static_templates:
#    - sitemap.html

#plugins:
#  - search:
#      prebuild_index: true

nav:
  - 'index.md'
  - 'Code': 'code.md'
  - 'Tasks': 'tasks.md'
  - 'Users': 'users.md'
  - 'Docs': 'docs.md'
  - 'PDFs': 'pdf.md'
  - 'Misc': 'misc.md'
  - 'Talks': 'talks.md'
