# This action rebuilds the docs whenever there is a change (push),
# and deplys it automatically on GitHub pages (the branch gh-pages).
#
name: Build and Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: pip3 install mkdocs
      - run: git pull
      - run: mkdocs -q build
      - run: mkdocs -q gh-deploy --ignore-version
