# This action runs on pull request in order to check
# that the proposed changes don't break the site.
#
name: Check a pull request
on:
  pull_request:
    branches: [ main ]
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: pip3 install mkdocs
      - run: mkdocs build --strict
